import './globals.css'
import type { Metadata } from 'next'
import localFont from "next/font/local"
import { Inter,  Montserrat } from 'next/font/google'
import Header from '@/components/Layout/Header/Header'
import Hero from '@/components/Home/Hero/Hero'


const inter = Inter({ 
  weight: [ '200', '300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'] 
})

const montserrat = Montserrat({
  weight: [ '200', '300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const ClashDisplay = localFont({
  src: [
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-ExtraLight.otf',
      weight: '200'
    },
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-Light.otf',
      weight: '300'
    },
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-Regular.otf',
      weight: '400'
    },
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-Medium.otf',
      weight: '500'
    },
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-Semibold.otf',
      weight: '600'
    },
    {
      path:'../../public/fonts/ClashDisplay_Complete/ClashDisplay-Bold.otf',
      weight: '700'
    },
  ],
  variable: '--font-ClashDisplay'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.className} ${ClashDisplay.variable} font-sans bg-primaryBg`}>
        <div>
          <Header />
          <Hero />
        </div>
        {children}
      </body>
    </html>
  )
}
